version: '3'
services:
  pgsql:
    image: postgres:9.6.17
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=webfleet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webfleet
    volumes:
      - ./pgsql:/var/lib/postgresql/data
  auth0:
    image: mockserver/mockserver
    ports:
    - 9999:1080
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mockserver-auth0.json
    volumes:
      - ../src/it/resources:/config
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "webfleet-domains:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock