POST http://localhost:8080/api/v1/domains
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnRzLnJlbW92ZSBkb21haW5zLnVwZGF0ZSB1c2Vycy5hZGQgdXNlcnMucmVtb3ZlIGNvbnRlbnRzLmluc2VydCIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkyMzM2NTkzfQ.cUMoNh0FoUTirxe9dkuRIr7k2GZKC6dujJu9q3tUZPKjEg1c16uXxg3et7cBFc5e99R1tgfAzV7lBloJl02D1mQKnAP9W6ZrNfAMxOhb_894GLL9-bZFORvSxkaZW2JQFH2yE9Z9NZicTbtdJD_8UJV2t0mr0ZrJDNcl-ayUZqbvELeivXjzGZXmdQpeM8xbXpOwx_Vmz9L7Xem568dwcHiBBpN-5QjophC9ArbYDUR_tnKIjqK3PLpqkeOu90M75_nu21TUlpgtxsbWmpAZXfivcHA5xb-TQ0Xp6Ud0_vi3wwmxYCua6bETDW5KUzFaVqJ6ORvDyFw16PQ7YwL_5QkOv3YrP26NZIvkGOKF3347bEeiJIUpKIN8Mpev3mlXu5wyK9s420KEZflcaxepkcpI_FiPakSH0KIqScRQqLSN_L0tTPkGTHzxjjdVls8n56Uo-Y1s1ugaEwk0UwuXrGmOkxL5f0vrTAMNM6Zv79CYWPns-gtGMTAMokGNID5wsZN2fclQe6qTmU4UsPFVv7p0AxmYjE5SHGuxFcvtpYF_i9CXpcaMxq3BsmgLnF3pwS76Xmu70cF9Ed4cuVAcjuL3rCbrcQ3uwT9D1HbZA9ANvb7nMNO46BOjr3kFLq8kqJgyiNCbZlQXRZ3NfvWAOpC9OxCOIiq6I57Vu8KYXqY

{
  "title": "Domain topic",
  "id": "domain-topic-2",
  "icon": "user"
}

###
GET http://localhost:8080/api/v1/domains/adding-users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkyMDcwNzA4fQ.cx8ttig-lJWr9AM_gXz-lun1MxPRM-a6mwybzMnhiF-Y4sfE3-CBJxKFrogbDoSfe3HMd_rSGQIoQzH7TcDSLUpQbpaCim2G0JRXOLLwLydWSJGHJT_mBhfL62Ep64ZqEWBJr6m6Y_ADF3Trz9bmUbWj2O_2xv6pJtHtYnotlnKTBUkGkeRtV0Xyn92XQ5ghx81Yn8CLH8x6126DPm1gr1HlRmo3eo5GXbmYrbIs4QAIrqk2h8-7EdE4FBYHENNa7zmFkFvvgRBYVAi9B1kGcZZqQNNDRG-DVowmYrp1mChrDwV6YCZsnhlOcfA1i1pGRBtIS6i7anU6LsZ4yUNwLuSaRbw9fO76T_Myqmjuu3c3N8SqXlQcbdAeCBn_0-KMcosH19zefXTfD7rjTJHMyjdSprqNBDiAeEQO2igypg8gUqzXQ2IIa-xaZQxVm36IIOxVAz0AgSNaTbhMJdsBPXRx1tNAFp4-32T3uF5G37ST5TlhpBXCa_lUrt6rFleR5Bea0CLLZMOlxcoD8m2fZuZZMI4o4xvOlcnIdWLarj3f8qJbj360c1PdRnZiUdkknGkiTGSaJZKNjTzITg0HOk45XxJBMA4FLPk56i_Y6noT8EJVI-f58gbyVfb5We8dPIPzyNNmuRV9oNwwi7bGEnOoV-AdB6gyyIfvv_6Ja64

###
POST http://localhost:8080/api/v1/domains/domain-topic-2/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnRzLnJlbW92ZSBkb21haW5zLnVwZGF0ZSB1c2Vycy5hZGQgdXNlcnMucmVtb3ZlIGNvbnRlbnRzLmluc2VydCIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkyMzM2NTkzfQ.cUMoNh0FoUTirxe9dkuRIr7k2GZKC6dujJu9q3tUZPKjEg1c16uXxg3et7cBFc5e99R1tgfAzV7lBloJl02D1mQKnAP9W6ZrNfAMxOhb_894GLL9-bZFORvSxkaZW2JQFH2yE9Z9NZicTbtdJD_8UJV2t0mr0ZrJDNcl-ayUZqbvELeivXjzGZXmdQpeM8xbXpOwx_Vmz9L7Xem568dwcHiBBpN-5QjophC9ArbYDUR_tnKIjqK3PLpqkeOu90M75_nu21TUlpgtxsbWmpAZXfivcHA5xb-TQ0Xp6Ud0_vi3wwmxYCua6bETDW5KUzFaVqJ6ORvDyFw16PQ7YwL_5QkOv3YrP26NZIvkGOKF3347bEeiJIUpKIN8Mpev3mlXu5wyK9s420KEZflcaxepkcpI_FiPakSH0KIqScRQqLSN_L0tTPkGTHzxjjdVls8n56Uo-Y1s1ugaEwk0UwuXrGmOkxL5f0vrTAMNM6Zv79CYWPns-gtGMTAMokGNID5wsZN2fclQe6qTmU4UsPFVv7p0AxmYjE5SHGuxFcvtpYF_i9CXpcaMxq3BsmgLnF3pwS76Xmu70cF9Ed4cuVAcjuL3rCbrcQ3uwT9D1HbZA9ANvb7nMNO46BOjr3kFLq8kqJgyiNCbZlQXRZ3NfvWAOpC9OxCOIiq6I57Vu8KYXqY

{
  "userName": "mep-user",
  "permissions": ["contents.insert"]
}

###
GET http://localhost:8080/api/v1/domains/domain-topic-2/users/mep-user/permissions

