POST http://localhost:8080/api/v1/domains
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQ6ZGVsZXRlIGNvbnRlbnQ6cmV2aWV3IGNvbnRlbnQ6Y3JlYXRlIGNvbnRlbnQ6cmVhZCBjb250ZW50OnB1Ymxpc2giLCJpc3MiOiJhdXRoMCIsImV4cCI6MTU5MjMxNTQ1OH0.dDQ_W9PRIrFs3Je0r2FAypRcHH6QVpnlWfQWyeW1WtOivzglESQPOO731baxAqXMBvc45kee5YGpy65Qv8hsah8Fm1dHzFDLn8yW0PrN6jE9C4XgGGqqjBpuRRwZLleSZkOMOmCg56v23jehrSnPPIEtcK3baxVEndmZyrGW4WOieqSuKZltpbv1jwvUxtZgaXqhQvgJ5_zHkf7UYoPCog4XsQGWruQRn_v8IZz-YDimDhYnaLqgMizJpB25y3PLbykH_8z9z2xdLyexFIcN5mQXbJxwqfiOyCyGtDCUBaM-tJBfYiBnLOaoFAr3-cqIH94g_vmWf0CMIvjXw3oSVyfqscttSshm_NAFxZswAZr2dZ_xvrDLtfnEPlPr4v5HoFSxJSk_mjREKw5oJIB8LoKTTKgzn-sQ7t1QPLl6_5lncZqNlFr2YbYJ5acLvLXe9HGuta1aYHBUm0Lhtxp59Lz79tV1rxmazATgJAPBH4eW-6iOd-v9Dppn8fsNndLk_PRsMt4dTfKaO6Y31TctMgTSR1l-Vv0Ex_JSaCIityvr_04sGzPzokwIVkD6Lc-vYUlf09WB0CLt_C7HoSmmEpuS3i0daN9-TqFqpa8O1H1yMtjnI9vdWtI0iPRq3EciOdipxrZHTNgtedwVJ3i-mIMoPf9HsYCBhHokf-1fPtc

{
  "title": "Domain topic",
  "id": "domain-topic-2",
  "icon": "user"
}

###
GET http://localhost:8080/api/v1/domains/adding-users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkyMDcwNzA4fQ.cx8ttig-lJWr9AM_gXz-lun1MxPRM-a6mwybzMnhiF-Y4sfE3-CBJxKFrogbDoSfe3HMd_rSGQIoQzH7TcDSLUpQbpaCim2G0JRXOLLwLydWSJGHJT_mBhfL62Ep64ZqEWBJr6m6Y_ADF3Trz9bmUbWj2O_2xv6pJtHtYnotlnKTBUkGkeRtV0Xyn92XQ5ghx81Yn8CLH8x6126DPm1gr1HlRmo3eo5GXbmYrbIs4QAIrqk2h8-7EdE4FBYHENNa7zmFkFvvgRBYVAi9B1kGcZZqQNNDRG-DVowmYrp1mChrDwV6YCZsnhlOcfA1i1pGRBtIS6i7anU6LsZ4yUNwLuSaRbw9fO76T_Myqmjuu3c3N8SqXlQcbdAeCBn_0-KMcosH19zefXTfD7rjTJHMyjdSprqNBDiAeEQO2igypg8gUqzXQ2IIa-xaZQxVm36IIOxVAz0AgSNaTbhMJdsBPXRx1tNAFp4-32T3uF5G37ST5TlhpBXCa_lUrt6rFleR5Bea0CLLZMOlxcoD8m2fZuZZMI4o4xvOlcnIdWLarj3f8qJbj360c1PdRnZiUdkknGkiTGSaJZKNjTzITg0HOk45XxJBMA4FLPk56i_Y6noT8EJVI-f58gbyVfb5We8dPIPzyNNmuRV9oNwwi7bGEnOoV-AdB6gyyIfvv_6Ja64

###
POST http://localhost:8080/api/v1/domains/adding-users/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkyMDg1MzUxfQ.aEUSdYrLoe5l4zeEcfFHH7tyzdPOWU0eN_nIlgeTNcRqrXKog0lDwTuLIBVReYQye7KqTXGOdbf7Bpe0GlEdDpCfOY_sFzv-Dz_T8c0HM8Q8P1iuzkr7JlsJQ-KtsXbhSYkEo_00jET-mj0SVjhukaOdx49L523pKmVT3_MKX-0uHeC90-xaRlvlWY_cnery_cjy4U4W0PPw263QPkmcIc1Ry7fue1MKElp6_WkOL1AswVLhx85vxiJvmbbTN1-OdOhKtNC66Z-KSRcw8BQ_zpjKEoBU4p8A0OS9DwnOLnw-2RKi46r3UMfecn7qvLtnn7yNJAjIhvhdgD464Hdm62p2xjeLGLeU_Bglz-lcsFr-CGev_o3LKK1Nk_5voJ0qHlDQJ15TIs8_2itn4qnctVW36gGx5enINoku5U-vKMEsAQAmCivdmh0UkTodnfhoAua_AfKtG_vy7P8fTJqoq2i9QVvpHiiO9hMJe8bzE7JRNJeA2M-D5oWB1LGR-S4m_r7RYzMkuh6gbfPtQ7hIfLa8as9fnNGA37mJSWhjMpET97L1_6qRUuiBB5v9A4cq10JtgiKffTg774fshalHGyJMAJX3c-ClLxsaG-Se2r4VvLGUedl4MruY-ii6Hrtflr3f3Lv1P3q2V_yLtf8gHuBpR-d5JILuG7CgkoBsWDU

{
  "userName": "mep-user",
  "permissions": ["contents.insert"]
}

###
GET http://localhost:8080/api/v1/domains/adding-users/permissions?user=mep-user&permission=contents.insert
