POST http://localhost:8080/api/v1/domains
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FWkdSRE0wTURZNE5EYzVSREE0UTBORU5qY3hRVE13TlRnMlJqTTBNMFU1TURrMk5UZ3lRUSJ9.eyJpc3MiOiJodHRwczovL2xkc29mdHdhcmUuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVlZWM5Nzk2MTBiZDEwMDAxOTUyNTM4YyIsImF1ZCI6WyJodHRwczovL2Rldi1lbnYud2ViZmxlZXQuY29tIiwiaHR0cHM6Ly9sZHNvZnR3YXJlLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE1OTI4NTAwMTcsImV4cCI6MTU5MjkzNjQxNywiYXpwIjoiVDJqcHJnUnpGc2NRMW9iMkcxTWIwMXJCbzZiMDV0MFciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiZG9tYWluczpyZWFkIl19.ritvOabobZe226uOo_Y5TI8XtVu8TNtNIysRmCS8MLMWFa-Sg7-SGnkyHu7qiKj_o0OTYbXDrNhJB8qMtjcPHHYdKobiqfSDZQL29IKf0Y1mihBf0-QczZPzPp0_9JU2fltMsvWjfnOvRN8GqNwQj66FRhtFw4pEtqAGsdyyLOoXRrwKn_Zj-aZ3flGQGRIkl2c0zjMqu56VhC8sAPBaaA_XfK-Jmdua-I8JOtp2aFDhxO_GHEfRgLvSV_-3Nr37oVN_rlu8l5MjsUZLIvk76-eQGrWB6jsDz4UDlkVL-wZRYlKvgszKVwdnDXpc8n3jTqWuZmP4CmCIG3apYu1tnw

{
  "title": "Domain topic",
  "id": "domain-topic-2",
  "icon": "user"
}

###
GET http://localhost:8080/api/v1/domains
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FWkdSRE0wTURZNE5EYzVSREE0UTBORU5qY3hRVE13TlRnMlJqTTBNMFU1TURrMk5UZ3lRUSJ9.eyJpc3MiOiJodHRwczovL2xkc29mdHdhcmUuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVlZWM5Nzk2MTBiZDEwMDAxOTUyNTM4YyIsImF1ZCI6WyJodHRwczovL2Rldi1lbnYud2ViZmxlZXQuY29tIiwiaHR0cHM6Ly9sZHNvZnR3YXJlLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE1OTI4NTAwMTcsImV4cCI6MTU5MjkzNjQxNywiYXpwIjoiVDJqcHJnUnpGc2NRMW9iMkcxTWIwMXJCbzZiMDV0MFciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiZG9tYWluczpyZWFkIl19.ritvOabobZe226uOo_Y5TI8XtVu8TNtNIysRmCS8MLMWFa-Sg7-SGnkyHu7qiKj_o0OTYbXDrNhJB8qMtjcPHHYdKobiqfSDZQL29IKf0Y1mihBf0-QczZPzPp0_9JU2fltMsvWjfnOvRN8GqNwQj66FRhtFw4pEtqAGsdyyLOoXRrwKn_Zj-aZ3flGQGRIkl2c0zjMqu56VhC8sAPBaaA_XfK-Jmdua-I8JOtp2aFDhxO_GHEfRgLvSV_-3Nr37oVN_rlu8l5MjsUZLIvk76-eQGrWB6jsDz4UDlkVL-wZRYlKvgszKVwdnDXpc8n3jTqWuZmP4CmCIG3apYu1tnw

###
POST http://localhost:8080/api/v1/domains/domain-topic-2/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnRzLnJlbW92ZSBkb21haW5zLnVwZGF0ZSB1c2Vycy5hZGQgdXNlcnMucmVtb3ZlIGNvbnRlbnRzLmluc2VydCIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkyMzM2NTkzfQ.cUMoNh0FoUTirxe9dkuRIr7k2GZKC6dujJu9q3tUZPKjEg1c16uXxg3et7cBFc5e99R1tgfAzV7lBloJl02D1mQKnAP9W6ZrNfAMxOhb_894GLL9-bZFORvSxkaZW2JQFH2yE9Z9NZicTbtdJD_8UJV2t0mr0ZrJDNcl-ayUZqbvELeivXjzGZXmdQpeM8xbXpOwx_Vmz9L7Xem568dwcHiBBpN-5QjophC9ArbYDUR_tnKIjqK3PLpqkeOu90M75_nu21TUlpgtxsbWmpAZXfivcHA5xb-TQ0Xp6Ud0_vi3wwmxYCua6bETDW5KUzFaVqJ6ORvDyFw16PQ7YwL_5QkOv3YrP26NZIvkGOKF3347bEeiJIUpKIN8Mpev3mlXu5wyK9s420KEZflcaxepkcpI_FiPakSH0KIqScRQqLSN_L0tTPkGTHzxjjdVls8n56Uo-Y1s1ugaEwk0UwuXrGmOkxL5f0vrTAMNM6Zv79CYWPns-gtGMTAMokGNID5wsZN2fclQe6qTmU4UsPFVv7p0AxmYjE5SHGuxFcvtpYF_i9CXpcaMxq3BsmgLnF3pwS76Xmu70cF9Ed4cuVAcjuL3rCbrcQ3uwT9D1HbZA9ANvb7nMNO46BOjr3kFLq8kqJgyiNCbZlQXRZ3NfvWAOpC9OxCOIiq6I57Vu8KYXqY

{
  "userName": "mep-user",
  "permissions": ["contents.insert"]
}

###
GET http://localhost:8080/api/v1/domains/domain-topic-2/users/mep-user/permissions

