name: build

on:
  push:
    branches:
      - master

jobs:


  release:
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login on docker registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Setup git username
        run: git config user.name LukeDS-it
      - name: Setup git email
        run: git config user.email ${{secrets.EMAIL}}
      - name: Setup git token
        run: git config user.password ${{secrets.TOKEN}}
      - name: Release
        run: sbt "release skip-tests with-defaults"
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
